site_name: NeIC SDA Operations handbook
extra_css: [css/neic-sda.css]
markdown_extensions:
  - callouts
plugins:
  - include-markdown
theme:
    name: readthedocs
nav:
  - Home: 'index.md'
  - 'Structure':
      - Introduction: 'structure.md'
      - Getting started: 'setup.md'
      - 'deploy.md'
      - Tests: 'tests.md'
  - 'Communication':
      - Database setup: 'db.md'
      - Encryption: 'encryption.md'
      - Data Submission: 'submission.md'
      - Interfacing with CEGA: 'connection.md'
  - 'Services':
      - SDA-Pipeline: 'services/pipeline.md'
      - 'services/ingest.md'
      - 'services/verify.md'
      - 'services/finalize.md'
      - 'services/backup.md'
      - 'services/mapper.md'
      - Data Retrieval API: 'dataout.md'
  - 'Guides':
      - Contributing: 'CONTRIBUTING.md'


      
