site_name: NeIC SDA Operations Handbook
extra_css: [css/neic-sda.css]
markdown_extensions:
  - callouts
plugins:
  - include-markdown
  - mermaid2
theme:
  name: readthedocs
nav:
  - Home: "index.md"
  - "Structure":
      - Introduction: "structure.md"
      - Getting started: "setup.md"
      - "deploy.md"
  - "Communication":
      - Database setup: "db.md"
      - Encryption: "encryption.md"
      - Data Submission: "submission.md"
      - Interfacing with CEGA: "connection.md"
  - "Services":
      - SDA: "services/sda.md"
      - "services/intercept.md"
      - "services/ingest.md"
      - "services/verify.md"
      - "services/finalize.md"
      - "services/mapper.md"
      - "services/syncapi.md"
      - "services/sync.md"
      - Data Retrieval API: "dataout.md"
  - "Guides":
      - Contributing: "CONTRIBUTING.md"
      - Local dev and testing: "guides/local-dev-and-testing.md"
      - Deploying with Kubernetes: "guides/deploy-k8s.md"
      - Troubleshooting: "guides/troubleshooting.md"
      