site_name: NeIC SDA
extra_css: [css/neic-sda.css]
markdown_extensions:
  - callouts
plugins:
  - include-markdown
theme:
    name: readthedocs
nav:
  - Getting started: setup.md
  - Database setup: db.md
  - Deployments and Local Bootstrap: deploy.md
  - Encryption: encryption.md
  - Data Submission: submission.md
  - Interfacing with CEGA: connection.md
  - Data Retrieval API: dataout.md
  - SDA-Pipeline: services/pipeline.md
  - Tests: tests.md
  - Contributing: CONTRIBUTING.md
