name: "Aggregate documentation"

on:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to aggregate documentation from'
        required: true
        default: "neicnordic/sensitive-data-archive"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get install -yq aspell
          pip3 install -q pyspelling

      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: bash aggregate-repositories.sh ${{ inputs.repository || 'neicnordic/sensitive-data-archive' }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          delete-branch: true
          labels: "automated pr"
          author: neicnordic <neicnordic@users.noreply.github.com>
