name: "Aggregate documentation"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to aggregate documentation from'
        required: true
        default: "neicnordic/sensitive-data-archive"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: bash aggregate-repositories.sh ${{ inputs.repository }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          labels: "automated pr"
          author: neicnordic <neicnordic@users.noreply.github.com>
